name: my-app

services:
  my-app-database:
    image: postgres:16
    container_name: my-app-database
    scale: 1
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      TZ: Europe/Paris
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d database -U julien"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    volumes:
      - my-app-database:/data/postgres

volumes:
  my-app-database:
